Fixed transitions for a large number of xnames
Cray-HPE/hms-power-control pull request #46
Opened 2024-10-11 15:05 UTC by shunr-hpe

## Summary and Scope

- Updated version to 2.5.0
- Added paging of transitions when they are stored in etcd for large requests
- Added truncating of the messages and error messages.

CASMHMS-6242

## Issues and Related PRs

* Resolves [CASMHMS-6242](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6239)

## Testing

Tested on:

  * Local development environment
 
Test description:

## Risks and Mitigations

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable

2025-01-06 14:59 UTC, jwlv commented
App version should be 2.7.0 in PR summary.

2025-01-06 15:52 UTC, jwlv requested changes
Because of the changes to etcd, should the new app version be 3.0.0 instead of 2.7.0?

2025-01-06 15:52 UTC, jwlv commented on internal/storage/storage_mem_impl.go
> +// (C) Copyright [2022-2024] Hewlett Packard Enterprise Development LP
2025

2025-01-06 15:52 UTC, jwlv commented on internal/model/transitions.go
> + * (C) Copyright [2021-2024] Hewlett Packard Enterprise Development LP
2025

2025-01-06 15:52 UTC, jwlv commented on internal/domain/transitions.go
> +		_, trOld, err := (*GLOB.DSP).GetTransition(tr.TransitionID)
Should this be ```trOld, _, err := ...```?  I'm guessing not, but just noticing that its different from the other calls to GetTransition.

2025-01-06 15:52 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +			e.Logger.Errorf("Expected last part to be an int in %s. %s", key0, err)
Should we continue if there's an error?

2025-01-06 15:52 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +			e.Logger.Errorf("Expected last part to be an int in %s, %s", key0, err)
Should we continue if there's an error?

2025-01-06 15:52 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +			e.Logger.Error(err)
Should we continue the loop if there's an error or break out so that err isn't overwritten by the next page attempt?  Otherwise, should probably be sure current non-nil err does get returned somehow?

2025-01-06 15:52 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +		e.Logger.WithFields(logrus.Fields{"TransitionID": transition.TransitionID, "Error": err}).Error("Error marshalling transition to json")
Seems like we should somehow cleanly unwind up the stack if there was an error?

2025-01-06 15:52 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +	originalSize, _ := getObjectSize(transition)
For this call to getObjectSize() and additional ones later, is there value in continuing if the transition couldn't be unmarshaled?  Should we check the error and return if so?

2025-01-06 15:52 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +func (e *ETCDStorage) breakIntoPagesIfNeeded(transition model.Transition, pageSize int) (model.Transition, []*model.TransitionPage) {
Seems like the three error cases in this function should be fatal?

2025-01-06 15:52 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +	if len(transition.Tasks) > pageSize || len(transition.Location) > pageSize {
Could check the inversion, and return transition,nil immediately.  Would avoid indenting the majority of the function.  Just a nit though and not necessary.

2025-01-06 15:52 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +			e.Logger.Error(err)
Return right away if error?

2025-01-06 15:52 UTC, jwlv commented on internal/storage/storage_etcd_impl_test.go
> +// (C) Copyright [2024] Hewlett Packard Enterprise Development LP
2025

2025-01-06 15:52 UTC, jwlv commented on internal/storage/transition_size_test.go
> +// (C) Copyright [2024] Hewlett Packard Enterprise Development LP
2025

2025-01-06 15:56 UTC, jwlv commented
PR description says tested local dev env only but was likely tested on an internal system as well?

2025-01-06 18:36 UTC, shunr-hpe commented on internal/domain/transitions.go
> +		_, trOld, err := (*GLOB.DSP).GetTransition(tr.TransitionID)
The first return value, includes all the data from all the pages.
The second return value, is just the transition data as it is stored in etcd for the first page.
The pages other than the first page only contain extra tasks, locations, and transitionTaskResp's. The other data about the transition is in the first page.
And so when one only needs to deal with this other data, and one wants to do a Test And Set (TAS) then they need to use the first page, which is the second argument.

2025-01-06 19:31 UTC, shunr-hpe commented on internal/storage/storage_etcd_impl.go
> +			e.Logger.Errorf("Expected last part to be an int in %s. %s", key0, err)
The consequence of not being able to sort is that the data in the pages may move around in the final presented transition's arrays of tasks, task responses, and locations (xnames).
These checks are "asserts" that shouldn't be possible. The code picks these key names, and it should always pick a number.
I think it is ok to leave it like this.
However tell me if you have a better solution.

2025-01-06 19:32 UTC, shunr-hpe commented on internal/storage/storage_etcd_impl.go
> +			e.Logger.Errorf("Expected last part to be an int in %s, %s", key0, err)
See the comment on key0Sufix. Tell me if you have a better solution.
I think that these cases can't happen. I think that I don't want the code to hard fail if they do happen.

2025-01-06 20:22 UTC, jwlv commented on internal/domain/transitions.go
> +		_, trOld, err := (*GLOB.DSP).GetTransition(tr.TransitionID)
Thanks for the explanation

2025-01-06 20:23 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +			e.Logger.Errorf("Expected last part to be an int in %s. %s", key0, err)
Sounds good leaving as is.

2025-01-06 20:23 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +			e.Logger.Errorf("Expected last part to be an int in %s, %s", key0, err)
Sounds good as is.

2025-01-06 20:58 UTC, shunr-hpe commented on internal/storage/storage_etcd_impl.go
> +func (e *ETCDStorage) breakIntoPagesIfNeeded(transition model.Transition, pageSize int) (model.Transition, []*model.TransitionPage) {
The errors are not fatal.
They should not happen.
If there is an unexpected case the given transition field will remain unchanged.
pageTasks, pageLocations, pageTaskIDs should return nil if the transition's value is nil. Otherwise it should at least return a first page.
For the cases that should not happen, I still checked the length to be sure to avoid an array out of bounds error, and I still logged the case.

2025-01-06 21:09 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +func (e *ETCDStorage) breakIntoPagesIfNeeded(transition model.Transition, pageSize int) (model.Transition, []*model.TransitionPage) {
Ok, sounds good!

2025-01-06 21:17 UTC, shunr-hpe commented on internal/storage/storage_etcd_impl.go
> +	originalSize, _ := getObjectSize(transition)
The size of the object is rarely needed. i.e. most power requests will not hit the max size.
If there is a problem marshaling the object, it will be hit when the object is stored in ectd.
My preference is to not make it fatal.

2025-01-06 21:35 UTC, shunr-hpe commented on internal/storage/storage_etcd_impl.go
> +			e.Logger.Error(err)
If there are pages, there is something that could be returned.
Most users of the pcs only care about the status on the transition.
I prefer to leave it as it is. I agree there are downsides to this. I am at least logging them.
What is your position? Is it that all errors produce an http error code? Unexpected errors would produce an http 500?

2025-01-06 21:57 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +	originalSize, _ := getObjectSize(transition)
Sounds good.

2025-01-06 22:01 UTC, jwlv commented on internal/storage/storage_etcd_impl.go
> +			e.Logger.Error(err)
I think its fine leaving as is.

2025-01-06 23:04 UTC, shunr-hpe commented
> PR description says tested local dev env only but was likely tested on an internal system as well?

I believe that I tested on mug. I'll test there again after making the next batch of changes.

2025-01-08 16:33 UTC, mbuchmann-hpe approved these changes

2025-01-08 17:07 UTC, jwlv approved these changes

2025-01-09 07:18 UTC, merged