Added support for ppprof builds
Cray-HPE/hms-power-control pull request #59
Opened 2024-12-23 20:31 UTC by jwlv

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable

2024-12-23 21:36 UTC, jacobsalmela approved these changes

2025-01-02 19:31 UTC, mbuchmann-hpe requested changes

2025-01-02 19:31 UTC, mbuchmann-hpe commented on Dockerfile
> +ARG ENABLE_PPROF=true
Should this be false???

2025-01-02 19:58 UTC, mbuchmann-hpe approved these changes

2025-01-02 20:17 UTC, jwlv commented on Dockerfile
> +ARG ENABLE_PPROF=true
Yes, but need set to 'true' for remaining testing.  Will set to 'false' in all Dockerfiles before committing changes to release branch.  Will leave this conversation unresolved until then as a reminder and to prevent accidental merging with it set to 'true'.

2025-01-03 22:38 UTC, shunr-hpe approved these changes

2025-01-09 17:23 UTC, jwlv commented on Dockerfile
> +ARG ENABLE_PPROF=true
Resolving as implementation is different now.

2025-01-09 17:24 UTC, merged